# Generated by Django 3.1.7 on 2021-04-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.PositiveIntegerField(verbose_name='Valor por unidad')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('valor_total', models.PositiveIntegerField(verbose_name='Valor total productos')),
                ('fecha_atencion', models.DateTimeField(blank=True, verbose_name='Fecha de atencion')),
            ],
        ),
        migrations.CreateModel(
            name='boletaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.boleta', verbose_name='boleta')),
            ],
        ),
    ]
